export const ALL_ARTICLES_REQUEST = 'ALL_ARTICLES_REQUEST'
export const ALL_ARTICLES_SUCCESS = 'ALL_ARTICLES_SUCCESS'
export const ALL_ARTICLES_FAIL = 'ALL_ARTICLES_FAIL'

export const NEW_ARTICLE_REQUEST = 'NEW_ARTICLE_REQUEST'
export const NEW_ARTICLE_SUCCESS = 'NEW_ARTICLE_SUCCESS'
export const NEW_ARTICLE_RESET = 'NEW_ARTICLE_RESET'
export const NEW_ARTICLE_FAIL = 'NEW_ARTICLE_FAIL'

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST'
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_RESET = 'UPDATE_ARTICLE_RESET'
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL'

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_RESET = 'DELETE_ARTICLE_RESET'
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL'

export const ARTICLE_DETAILS_REQUEST = 'ARTICLE_DETAILS_REQUEST'
export const ARTICLE_DETAILS_SUCCESS = 'ARTICLE_DETAILS_SUCCESS'
export const ARTICLE_DETAILS_FAIL = 'ARTICLE_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'