export const ALL_ARTICLES_SUCCESS = 'ALL_ARTICLES_SUCCESS'
export const ALL_ARTICLES_FAIL = 'ALL_ARTICLES_FAIL'

export const ARTICLE_DETAILS_SUCCESS = 'ARTICLE_DETAILS_SUCCESS'
export const ARTICLE_DETAILS_FAIL = 'ARTICLE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'